<a href="https://colab.research.google.com/github/cheshtabiala/MLlab1/blob/main/MLlab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

(a)Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
import numpy as np

In [ ]:
array=np.array([1,2,3,4,5])
reversed_array= array[::-1]
reversed_array

AttributeError: ignored

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods


In [ ]:
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flattened_array= array1.flatten()
flattened_array
raveled_array = array1.ravel()
raveled_array

NameError: ignored

(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])


In [ ]:
import numpy as np
arr1= np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
compare=np.array_equal(arr1,arr2)
compare

True

(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
x
y
mostfrequent_x= np.bincount(x).argmax()
indices_x=np.where(x==mostfrequent_x),[0]

mostfrequent_x
indices_x
mostfrequent_y= np.bincount(y).argmax()
indices_y=np.where(x==mostfrequent_y),[0]

mostfrequent_y
indices_y

ValueError: ignored

e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


In [ ]:
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
gfg
totalsum=np.sum(gfg)
totalsum
rowsum=np.sum(gfg,axis=1)
rowsum
colsum=np.sum(gfg,axis=0)
colsum

matrix([[20,  9, 16]])

(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [ ]:
n_array=np.array([[55,25,15],[30,44,2],[11,45,77]])
diagonalsum=np.trace(n_array)
eigenvalues,_=np.linalg.eig(n_array)

_,eigenvectors=np.linalg.eig(n_array)
inverse=np.linalg.inv(n_array)
determinant=np.linalg.det(n_array)
print(diagonalsum,"'|'",
eigenvalues,_,"'|'",
_,eigenvectors,"'|'",
inverse,"'|'",
determinant)

176 '|' [98.16835147 28.097044   49.73460452] [98.16835147 28.097044   49.73460452] '|' [98.16835147 28.097044   49.73460452] [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] '|' [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] '|' 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [ ]:
p=np.matrix([[1,2],[2,3]])
q=np.matrix([[14,5],[6,7]])
print(p)
print(q)
result=np.dot(p,q)
cov_mat=np.cov(p,q)

[[1 2]
 [2 3]]


matrix([[14,  5],
        [ 6,  7]])

(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

The inner product produces a scalar that measures the similarity or projection of one vector onto another.
The outer product produces a matrix that encodes pairwise interactions between elements of two vectors.
The Cartesian product generates a set of all possible ordered pairs from two sets, representing combinations of elements.

In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
innerproduct=np.inner(x,y)
outerproduct=np.outer(x,y)
print(innerproduct,"|",outerproduct)
caretsianproduct=np.einsum('ij,ik->ijk', x, y)
print(caretsianproduct)

[[17 52]
 [13 62]] | [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[[ 2 10  0]
  [ 3 15  0]
  [ 4 20  0]]

 [[15 30  9]
  [10 20  6]
  [45 90 27]]]


Q2: Based on NumPy Mathematics and Statistics
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row


In [ ]:

import numpy as np

array = np.array([[1, -2, 3],[-4, 5, -6]])

# i. Find element-wise absolute value
absolute_array = np.abs(array)

# ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
percentiles = np.percentile(array, [25, 50, 75])
percentiles_column = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)

# iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_dev_column = np.std(array, axis=0)
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_dev_row = np.std(array, axis=1)


Q2: Based on NumPy Mathematics and Statistics(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# Find floor, ceiling, and truncated value, rounded values
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements
(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)

# ii. Indices of sorted array
sorted_indices = np.argsort(array)

# iii. 4 smallest elements
smallest_elements = np.partition(array, 4)[:4]

# iv. 5 largest elements
largest_elements = np.partition(array, -5)[-5:]
print(sorted_array,sorted_indices,smallest_elements,largest_elements )

[ 10  16  16  52  54  62 453] [0 3 4 1 5 2 6] [16 10 16 52] [ 16  52  62  54 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
int_elements = array[array.astype(int) == array]

# ii. Float elements only
float_elements = array[array.astype(int) != array]
print(int_elements,float_elements)

[1. 2. 3. 2.] [1.2 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)
(b) Load the saved file into jupyter notebook?

In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    try:
        image = Image.open("Screenshot 2023-07-28 at 11.07.30 PM.png")
        array = np.array(image)

        if len(array.shape) == 2:
            # Grey scale image
            np.savetxt("grey_scale_image.txt", array, fmt='%d')
        elif len(array.shape) == 3:
            # RGB image
            np.savetxt("rgb_image.txt", array.reshape(-1, 3), fmt='%d')
        else:
            print("Unsupported image format.")
    except Exception as e:
        print("Error:", e)

# Usage example:
# img_to_array("your_image_path.jpg")


grey_scale_data = np.loadtxt("grey_scale_image.txt", dtype=int)
rgb_data = np.loadtxt("rgb_image.txt", dtype=int)
rgb_image = rgb_data.reshape(image_height, image_width, 3)



FileNotFoundError: ignored